### ISSUE TITLE
你好为什么最近东东农场都跑不了

### ISSUE THREAD

**Issue by Ginua8292** [gys619/Absinthe#50]
❗️东东农场日常任务, 错误!
TypeError: Cannot read properties of undefined (reading 'farmUserPro')
    at jdFruit (/ql/scripts/gys619_Absinthe_main/jd_fruit_task.js:104:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/gys619_Absinthe_main/jd_fruit_task.js:81:13

**Comment by gys619** [comment]
jd_fruit能跑不

**Comment by Ginua8292** [comment]
❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'farmUserPro')
    at jdFruit (/ql/scripts/gys619_Absinthe_main/jd_fruit.js:91:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/gys619_Absinthe_main/jd_fruit.js:74:7 
同样不能跑

**Comment by Ginua8292** [comment]
东东农场三个脚本都不能跑

**Comment by gys619** [comment]
删了重拉一下试试

**Comment by Ginua8292** [comment]
是不是缺了依赖呢？重拉了几次都是一样的报错！
